spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: iam_route
              uri: ${IAM_ROUTE_URI:http://localhost:8081}
              predicates:
                - Path=/authentication/**,/users/**
              filters:
                - PrefixPath=/api/v1
            - id: challenges_route
              uri: ${CHALLENGES_ROUTE_URI:http://localhost:8082}
              predicates:
                - Path=/challenges/**,/solutions/**,/tests/**
              filters:
                - PrefixPath=/api/v1